name: Nixie CI Pipeline

# Define when to trigger the workflow
on:
  pull_request:
    branches:
      - main  # This means the workflow runs when a pull request is made to the "main" branch.

jobs:
  test:
    # Define the job named "test" to run on a specific operating system
    name: Run Tests
    runs-on: ubuntu-latest  # The job will run on the latest version of Ubuntu (Linux)

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2  # This action pulls your code from the repository

      # Step 2: Set up Python in the environment
      - name: Set up Python
        uses: actions/setup-python@v2  # This action sets up Python
        with:
          python-version: '3.9'  # We're using Python version 3.9 for this project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Updates pip, the Python package installer
          pip install -r requirements.txt  # Installs the dependencies listed in requirements.txt

      # Step 4: Run tests using pytest
      - name: Run tests
        run: |
          pytest  # This command runs all the tests using pytest

